# Generated by Django 2.2.3 on 2020-05-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='numero',
        ),
        migrations.AddField(
            model_name='budget',
            name='number',
            field=models.CharField(blank=True, max_length=11, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Descuento'),
        ),
    ]
