# Generated by Django 2.2.3 on 2019-12-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='numero',
            field=models.IntegerField(auto_created=True, default=1, unique=True, verbose_name='Numero'),
            preserve_default=False,
        ),
    ]
