# Generated by Django 2.2.3 on 2019-12-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budget_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('B', 'Borrador'), ('E', 'Enviado'), ('A', 'Aprobado'), ('F', 'Finalizado')], default='B', max_length=1, verbose_name='Estado'),
        ),
    ]
