# Generated by Django 2.2.3 on 2020-05-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_auto_20200502_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='commercial_terms',
            field=models.TextField(blank=True, default='', verbose_name='Terminos Comerciales'),
        ),
    ]
