# Generated by Django 2.2.3 on 2019-12-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_budget_delivery_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetdetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Precio Venta'),
        ),
    ]
