# Generated by Django 2.2.3 on 2019-12-17 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telephone',
            old_name='name',
            new_name='description',
        ),
    ]
