# Generated by Django 2.2.3 on 2019-12-26 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20191226_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.Address_Type', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.City', verbose_name='Ciudad'),
        ),
    ]
